//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FPSEntity.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemDetail
    {
        public int Id { get; set; }
        public string ItemName { get; set; }
        public Nullable<int> PackgingID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> Total { get; set; }
        public string WeightType { get; set; }
        public Nullable<int> Dimention_Length { get; set; }
        public Nullable<int> Dimention_Width { get; set; }
        public Nullable<int> Dimention_Height { get; set; }
        public string HightUnit { get; set; }
        public Nullable<double> FrightClass { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public int QuoteID { get; set; }
        public string UserId { get; set; }
    
        //public virtual AspNetUsers AspNetUser { get; set; }
    }
}
