//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FPS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarriersDetail
    {
        public int Id { get; set; }
        public string CarriersDetails { get; set; }
        public Nullable<int> TransitTime { get; set; }
        public Nullable<double> DiscountedPrice { get; set; }
        public string CarriersLogo { get; set; }
        public Nullable<System.DateTime> CreatedDAte { get; set; }
        public string QuoteID { get; set; }
    }
}
