//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FPS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemCollectionAddress
    {
        public int UserShipmentDetailId { get; set; }
        public string Longitude { get; set; }
        public string Latitude { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public System.DateTime SpecificDateTime { get; set; }
        public int SpecificDateAttribute { get; set; }
        public int Id { get; set; }
        public string StartCurrentLocation { get; set; }
    }
}
