//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FPS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShipmentDetail
    {
        public int ShipmentId { get; set; }
        public string ItemdetailsDesc { get; set; }
        public string PackagingID { get; set; }
        public string ItemCondition { get; set; }
        public string Quantity { get; set; }
        public string Quantity_Length { get; set; }
        public string Quantity_Width { get; set; }
        public string Quantity_Height { get; set; }
        public string Commodity_Category { get; set; }
        public string NMFC_Code { get; set; }
        public string Isfreight_Insurance { get; set; }
        public string TotalValue_Shipment { get; set; }
        public string QuoteID { get; set; }
        public string ItemName { get; set; }
    }
}
